Feature/main pages clone
Mi4-04/movies-front pull request #7
Opened 2022-03-02 10:35 UTC by Mi4-04

2022-03-02 12:31 UTC, Isidora25 approved these changes

2022-03-02 12:31 UTC, Isidora25 commented on src/App.tsx
> +  const [genres, setGenres] = React.useState<IGenre[]>([]);
А ты же импортируешь напрямую useState, почему обращаешься через React?

2022-03-02 12:31 UTC, Isidora25 commented on src/App.tsx
> +  React.useEffect(() => {
Аналогично можно импортировать напрямую

2022-03-02 12:31 UTC, Isidora25 commented on src/App.tsx
> +  const [view, setView] = React.useState<boolean>(false);
А что значит эта переменная? вид = true

2022-03-02 12:31 UTC, Isidora25 commented on src/utils/movies.ts
> +    if (localStorage.getItem("filmsIds") === null)
а что если там undefined?

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/Popularity/index.tsx
> +        value={props.voteAverage}
Лучше сразу сделать деструктуризацию пропсов в объявлении компонента [1]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/Popularity/index.tsx
> +  const handleChange = (e: any) => {
Не стоит использовать any без крайней необходимости. Здесь у тебя тип аргумента вполне известен [2]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/Popularity/index.tsx
> +        step={0.1}
magic numbers. Старайся все числовые и строковые константы выносить в неизменяемые переменные с говорящим именем

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/YearSelect/index.tsx
> +export const YearSelect = (props: {
см [1]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/YearSelect/index.tsx
> +  setYear: (value: any) => void;
см [2]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/YearSelect/index.tsx
> +  const [date, setDate] = React.useState<number[]>([]);
Как часто меняется список лет для отображения? Действительно здесь нужен стейт для хранения этой информации?

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/YearSelect/index.tsx
> +  const handleChange = (e: any) => {
см [2]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/component/YearSelect/index.tsx
> +            return (
return не нужен

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/Filtration/index.tsx
> +export const Filtration = (props: {
см [1]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemBlock/index.tsx
> +  film: any;
[2]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemBlock/index.tsx
> +export const MoviesItemBlock = (props: {
[1]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemBlock/index.tsx
> +          image={`${URL_POST}${props.film.poster_path}`}
деструктурируй свойства объекта film

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemBlock/index.tsx
> +            onClick={() => props.saveFilm(props.film.id)}
Лучше вынести в отдельную переменную функцию, а будет создаваться новая на каждый рендер [3]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemList/index.tsx
> +          onClick={() => props.saveFilm(props.film.id)}
[3]

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/index.tsx
> +      props.genres
Кусок кода очень плохо читается. Создай отдельную переменную, в которую ты будешь складывать айдишники жанров, а потом спокойно передавай ее в setGenresId

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/index.tsx
> +        .filter((w, index) => {
А что ты пытаешься здесь этим фильтром найти так сложно? 
Для чего тебе w? 
О чем говорит переменная w? 

Если тебе нужно найти все жанры, которых isClick === true достаточно просто обратиться к этому полю

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/index.tsx
> +        .map((genre) => {
Если опять-таки я все правильно понимаю, то возвращать только айдишники жанров можно прямо из filter

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/Main/component/FavoriteMovies/component/FavoriteMoviesItemLIst/style.ts
> +interface IMovie {
Повторение кода. Вынеси этот интерфейс в специальный файл с типами и импортируй оттуда везде, где он нужен

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +  let [movies, setMovies] = React.useState<any[]>([]);
any

2022-03-02 12:31 UTC, Isidora25 commented on src/Pages/Main/index.tsx
> +        <Link to="/add">
Так button или link?

2022-03-02 12:31 UTC, Isidora25 commented on src/components/GenreList/index.tsx
> +  setGenres: (value: any) => void;
any

2022-03-02 12:31 UTC, Isidora25 commented on src/components/GenreList/index.tsx
> +  console.log("123", genresId);
Логи

2022-03-02 12:31 UTC, Isidora25 commented on src/components/GenreList/index.tsx
> +    setGenresId(
где-то  я уже видела этот код
Если код повторяется, его следует выносить в отдельный компонент и переиспользовать

2022-03-02 12:31 UTC, Isidora25 commented on src/components/GenreList/index.tsx
> +  localStorage.setItem("genres", JSON.stringify(props.genres));
А для чего это сохраняется каждый рендер в LS?

2022-03-02 12:33 UTC, Isidora25 requested changes

2022-03-02 12:33 UTC, Isidora25 commented on package.json
> +    "@mui/icons-material": "^5.4.4",
А почему часть кода написана с помощью material-ui, а другая с помощью tw? А где-то голый styled-components?

2022-03-02 12:41 UTC, Mi4-04 commented on src/App.tsx
> +  const [view, setView] = React.useState<boolean>(false);
Это флаг для того чтобы делать блочный или строчный вид списка

2022-03-02 12:43 UTC, Mi4-04 commented on src/Pages/Main/index.tsx
> +        <Link to="/add">
ButtonLayout это из стилей а Link оборачивает Button

2022-03-02 12:44 UTC, Mi4-04 commented on package.json
> +    "@mui/icons-material": "^5.4.4",
Что именно поправить тут ?

2022-03-02 12:46 UTC, Isidora25 commented on src/App.tsx
> +  const [view, setView] = React.useState<boolean>(false);
Ну вот не всегда же к тебе за справкой обращаться, согласись. Нужно назвать переменную так, чтобы было понятно, что она делает

2022-03-02 12:48 UTC, Isidora25 commented on src/Pages/Main/index.tsx
> +        <Link to="/add">
Ну тут нужно что-то одно, либо ссылка, которая выглядит как кнопка, либо кнопка, которая выглядит как ссылка. 
По смыслу, если элемент делает редирект куда-то - это ссылка. Если есть обработчик клика - это кнопка

2022-03-02 12:48 UTC, Mi4-04 commented on src/App.tsx
> +  React.useEffect(() => {
Так как мне лучше через React. или напрямую ?

2022-03-02 12:49 UTC, Isidora25 commented on package.json
> +    "@mui/icons-material": "^5.4.4",
Ну по ТЗ как стили должны быть написаны?

2022-03-02 12:49 UTC, Mi4-04 commented on src/App.tsx
> +  const [view, setView] = React.useState<boolean>(false);
Понял, переименную

2022-03-03 06:18 UTC, Isidora25 requested changes

2022-03-03 06:18 UTC, Isidora25 commented on src/App.tsx
> +  const [blockAndListview, setBlockAndListview] =
А если blockAndListview = true - это какой вид? Блочный или список?

2022-03-03 06:18 UTC, Isidora25 commented on src/App.tsx
> +  localStorage.setItem("genres", JSON.stringify(genres));
Сделай так, чтобы перезаписывалось только когда нужно

2022-03-03 06:26 UTC, Mi4-04 commented on src/App.tsx
> +  const [blockAndListview, setBlockAndListview] =
Блочный

2022-03-03 15:10 UTC, Isidora25 requested changes

2022-03-03 15:10 UTC, Isidora25 commented on src/App.tsx
> +        return genre.id;
FYI return не нужен

2022-03-03 15:10 UTC, Isidora25 commented on src/App.tsx
> +        return genre.isClick;
FYI return не нужен

2022-03-03 15:10 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemBlock/index.tsx
> +    let newfilmsIds = [...filmsIds, id];
newfilmsIds где-то еще изменяется? Если нет, то зачем  `let`?

2022-03-03 15:10 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemList/index.tsx
>  interface IMoviesItemList {
https://github.com/Mi4-04/movies-front/pull/7/commits/6569f6fb68758aac269632cfdce3415ae9040eb5#diff-7b47e345642209293d9afb7d8128c0f62efc7a4fe71787991f87fe7d096f29e1R13 дубликат интерфейса

2022-03-03 15:10 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/component/MoviesItemList/index.tsx
> +  const saveFilm = (id: number): void => {
А зачем ты вынес это в дочерние компоненты? 
Теперь код задублировался

2022-03-03 15:10 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/index.tsx
> +  const [movies, setMovies] = React.useState<any[]>([]);
а сюда `IMovies` не подойдет разве?

2022-03-04 08:01 UTC, Isidora25 approved these changes

2022-03-04 08:04 UTC, merged