Movie update graphql
Mi4-04/movies-front pull request #9
Opened 2022-03-28 07:32 UTC by Mi4-04

2022-03-28 07:55 UTC, reshetov commented on src/Pages/AddPage/component/MoviesList/index.tsx
> +  const { data, loading } = useQuery(GET_ALL_MOVIES, {
Не знаю что у тебя на беке, но так работать не будет. API отдает фильмы постранично а тут у тебя нет page от слова совсем. Либо я что-то не знаю, либо ты работаешь только с первой страницей фильмов.

2022-03-28 07:55 UTC, reshetov commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +  let newFilmsIds = movies.map((film) => (movieId = film.id));
Чет тут какая-то странная логика, у тебя после этого прогона в movieId будет ПОСЛЕДНИЙ id из movies.
Если тебе нужен какой-то определенный - то для этого filter есть, или я что-то не понимаю

2022-03-28 07:55 UTC, reshetov commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +    movies.map((movie) => (filmId = movie.id));
И тут тоже

2022-03-28 07:55 UTC, reshetov commented on src/gql/mutation/index.ts
> -      ...CoreMovieFields
А зачем ты убрал фрагмент?

2022-03-28 07:55 UTC, reshetov commented on src/App.tsx
> +                <Main
Если уж ты решил тут сразу и авторизацию припилить, то этот роутинг должен быть приватным. Без авторизации только логин доступен

2022-03-28 07:55 UTC, reshetov commented on src/App.tsx
> +              <Route path="/add">
И этот тоже

2022-03-28 08:37 UTC, Isidora25 requested changes

2022-03-28 08:37 UTC, Isidora25 commented on src/utils/user.tsx
> +  const [users, setUser] = useState(jwtToken);
users?

2022-03-28 08:37 UTC, Isidora25 commented on src/utils/user.tsx
> +  user: null;
А что за тип такой, `null`?

2022-03-28 08:37 UTC, Isidora25 commented on src/utils/user.tsx
> +  signIn: (data: string) => void;
data? какая data? 
Ты сам не знаешь, что туда передаешь? 
Через месяц сам не вспомнишь, что за data
Назови нормально, чтобы не одному тебе было понятно, что передается в качестве аргументов

2022-03-28 08:37 UTC, Isidora25 commented on src/utils/user.tsx
> +      setUser(token);
почему в user хранится только token?

2022-03-28 08:37 UTC, Isidora25 commented on src/utils/user.tsx
> +    setUser(null);
Если не ошибаюсь, тут еще и кеш чистить нужно 
Проверь документацию аполло клиента

2022-03-28 08:37 UTC, Isidora25 commented on src/Pages/Login/index.tsx
> +  const context = React.useContext(AuthContext);
почему бы не сделать деструктуризацию и сразу получить нужные данные из контекста?

2022-03-28 08:37 UTC, Isidora25 commented on src/Pages/Login/index.tsx
> +  const context = React.useContext(AuthContext);
Почему в одном месте в проекте useContext импортируется из библиотеки React, а здесь иначе? 
Придерживайся единого стиля в коде, это важно

2022-03-28 08:37 UTC, Isidora25 commented on src/Pages/Login/index.tsx
> +  const onSubmit = (data: ILogin) => {
используй деструктуризацию

2022-03-28 08:37 UTC, Isidora25 commented on src/Pages/Login/index.tsx
> +        context.signIn(data.signIn.accessToken);
Вот я тут не очень понимаю, почему signIn - это объект теперь?
У тебя это описано как функция в контексте

2022-03-28 08:37 UTC, Isidora25 commented on src/Pages/Login/index.tsx
> +      onCompleted: (data) => {
опять data 
В одной функции две переменных  с именем data 
Очень не информативно и серьезно сбивает с толку.

2022-03-28 08:37 UTC, Isidora25 commented on src/components/PrivateRouter/index.tsx
> +        !user ? <Component {...props} /> : <Redirect to="/" />
Вообще не понимаю смысл этого кастомного роута 
Auth - это какой? приватный или публичный? 
Логично было бы предположить, что ты хотел сделать приватный роут. 
Но почему тогда ты рендеришь компонент, если юзер не определен? 
Получается, ты отправляешь на статичный роут, если юзер залогинен? 

очень странная логика

2022-03-28 08:37 UTC, Isidora25 commented on src/index.tsx
> +  <Suspense fallback={<div>Loading...</div>}>
Я надеюсь, что ты используешь экспериментальный функционал полностью принимая всю ответственность и понимая, что это может тебе выстрелить в ногу

2022-03-29 10:49 UTC, Isidora25 requested changes

2022-03-29 10:49 UTC, Isidora25 commented on src/Pages/AddPage/component/MoviesList/index.tsx
> +    event: React.ChangeEvent<unknown>,
Если тебе приходится объявлять параметр функции, но в использовании он тебе не нужен, используй знак нижнего подчеркивания _

2022-03-29 10:49 UTC, Isidora25 commented on src/utils/user.tsx
> +  token: any;
какие типы тут могут быть?

2022-03-29 10:49 UTC, Isidora25 commented on src/utils/user.tsx
> +  signIn: (token: string) => void;
а здесь token:string

2022-03-29 14:14 UTC, Isidora25 approved these changes

2022-03-30 06:45 UTC, reshetov commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +  let newFilmsIds = movies.filter((film) => (movieId = film.id));
Как я вижу эту логику, ты объявляешь переменную movieId и потом в итераторе filter пробегаешься по всем фильмам и каждый раз присваиваешь этой переменной значение id от фильма.
Итого: у тебя после этого перебора в movieID будет id ПОСЛЕДНЕГО фильма из массива.
Вопрос: А зачем все это? И если уж тебе вот прям зачем-то нужен тот ID можно сразу его по индексу взять. Но больше это на какой-то костыль похоже

2022-03-30 06:45 UTC, reshetov commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +    movies.filter((movie) => (filmId = movie.id));
См. коммент выше

2022-03-30 06:45 UTC, reshetov commented on src/config/apolloClient.ts
> +const httpLink = createHttpLink({ uri: "http://localhost:4000/graphql" });
Вынеси в URL в переменную окружения

2022-03-30 10:14 UTC, reshetov commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +  let newFilmsIds = movies.map((film) => film.id);
Ну допустим теперь ты собираешь массив из id. Вопрос остается тем-же - а зачем? Для чего вообще хранить ids фильмов что тебе вернул API?

2022-03-30 10:14 UTC, reshetov commented on src/Pages/Main/component/FavoriteMovies/index.tsx
> +  let newFilms = movies.find((film) => film.id);
1. film(s) - Это множественное число, а find отдает один объект
2. Подумай, а точно тебе нужна это строка?

2022-04-04 08:16 UTC, Isidora25 requested changes

2022-04-04 08:16 UTC, Isidora25 commented on src/Pages/Main/component/FavoriteMovies/component/FavoriteMoviesItem/index.tsx
> +  const [watched, setWatched] = React.useState<any>(
any?

2022-04-04 08:16 UTC, Isidora25 commented on src/Pages/Main/component/FavoriteMovies/component/FavoriteMoviesItem/index.tsx
> +    JSON.parse(String(localStorage.getItem(String(film.id))))
Что-то странное тут происходит

watched - судя по названию, boolean 
localStorage.getItem - возвращает string  или null 

для чего JSON.parse?

2022-04-04 08:16 UTC, Isidora25 commented on src/Pages/Main/component/FavoriteMovies/component/FavoriteMoviesItem/index.tsx
> +  film,
Используй сразу деструктуризацию, чтобы не тащить везде film

2022-04-04 09:42 UTC, Isidora25 approved these changes

2022-04-04 11:51 UTC, reshetov approved these changes

2022-04-04 11:53 UTC, merged